apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-consumer
  name: udaconnect-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-consumer
  template:
    metadata:
      labels:
        service: udaconnect-consumer
    spec:
      containers:
      - image: mehtadhiraj/udaconnect-consumer:latest
        name: udaconnect-consumer
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: locations-env
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: locations-env
              key: KAFKA_TOPIC
      restartPolicy: Always